### ISSUE TITLE
Why the scores in the paper are different from the scores here？

### ISSUE THREAD

**Issue by yxdr** [yafuly/CoGnition#2]
In your paper, you report character-level BLEU scores. But the scores in the paper are very different from the scores here https://github.com/yafuly/CoGnition/blob/master/README.md#baseline . Is it because you use word-level BLEU here?

**Comment by yafuly** [comment]
Hi,

Regarding the results' difference, there are three reasons:
(1) The CTER scores in the paper are evaluated by professional translators, whereas in the Github page the scores are based on automatic evaluation, which is efficient and consistent.
(2) Both the paper and the Github page report the character-level BLEU scores, as shown in line 22 in `CoGnition/scripts/infer-one-click-run.sh'. The major difference is due to the misuse of tokenization in the paper and we've announced it on the Github page:
_Note that: (A) The BLEU score on the CG-test set is different from the results in our paper due to mistakes in handling Chinese punctuations._ 
(3) The paper results are obtained by training and inferring with a single model, whereas the Github results are obtained by averaging the results of multiple runs with different seeds.

**Comment by yxdr** [comment]
> Hi,
> 
> Regarding the results' difference, there are three reasons: (1) The CTER scores in the paper are evaluated by professional translators, whereas in the Github page the scores are based on automatic evaluation, which is efficient and consistent. (2) Both the paper and the Github page report the character-level BLEU scores, as shown in line 22 in `CoGnition/scripts/infer-one-click-run.sh'. The major difference is due to the misuse of tokenization in the paper and we've announced it on the Github page: _Note that: (A) The BLEU score on the CG-test set is different from the results in our paper due to mistakes in handling Chinese punctuations._ (3) The paper results are obtained by training and inferring with a single model, whereas the Github results are obtained by averaging the results of multiple runs with different seeds.

Thank you.

**Comment by leileilin** [comment]
> 

But there is a big gap between the two in BLEU. I'm curious. almost 20.
